(corrected) Main profile is made on account creation
rvtr/rvtrx-api-account pull request #74
Opened 2021-02-15 15:15 UTC by joshwingreene

Closes #63

2021-02-16 19:24 UTC, fredbelotte commented
where are we with this?

2021-02-16 20:10 UTC, joshwingreene commented
@fredbelotte This PR is ready to be reviewed. I forgot to add you as a reviewer.

2021-02-16 21:59 UTC, fredbelotte requested changes

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Context/AccountContext.cs
>          new AccountModel
let's reduce to 1 complete account

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Domain/Models/AccountModel.cs
> +    [Required(ErrorMessage = "First name required")]
remove the capitalization rule on Name, where is LastName

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Domain/Models/AccountModel.cs
> +    [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$", ErrorMessage = "Last name must start with a capital letter and only use letters.")]
remove capitalization rule,

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Domain/Models/AccountModel.cs
> +      if (string.IsNullOrEmpty(FirstName))
this is handled by the Required attribute

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Domain/Models/ProfileModel.cs
> +    public bool IsAccountHolder { get; set; }
is this not handled by the account, why allowing Set here?

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Domain/Models/AccountModel.cs
> +    public string FirstName { get; set; }
doesn't Name part of the Profile already?

2021-02-16 21:59 UTC, fredbelotte commented on aspnet/RVTR.Account.Testing/Tests/RepositoryTest.cs
> +      // using (var ctx = new AccountContext(Options))
remove commented code

2021-02-18 19:47 UTC, joshwingreene commented
@fredbelotte All of the issues that you pointed out have been fixed and this PR is ready for review again.

2021-02-18 21:37 UTC, fredbelotte approved these changes
add new issue to refactor profileModel and accountModel
add new issue to update the unit tests

2021-02-18 21:39 UTC, merged